name: Run Scraper on Schedule and Push

on:
  # Run every 12 hours
  schedule:
    - cron: "0 1 * * *"
  # Run on every push to the repository
  push:
    branches:
      - main  # Adjust to the branch you want to monitor (e.g., main or master)
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Optional: print files
    - name: List all files
      run: ls -R
    
    - name: Print working directory
      run: pwd

    - name: Check SQLite Version
      run: sqlite3 --version

    - name: Verify database file
      run: |
        if [ -f "assets/immo_elliza.db" ]; then
          echo "Database file exists";
        else
          echo "Database file is missing";
          exit 1;
        fi
    
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9" # Replace with the Python version your script requires

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the script
    - name: Run scraper
      run: |
        python scraper.py
